name: "build-tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build_eppp:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        idf_ver: ["release-v6.0", "release-v5.5", "release-v5.4", "release-v5.3"]
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout esp-protocols
        uses: actions/checkout@v3
      - name: Build with IDF-${{ matrix.idf_ver }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          cd libssh
          ./install.sh
          cd examples/server
          idf.py build
          if [ "${{matrix.idf_ver}}" == "release-v5.5" ]; then
            cd ../esp_ssh
            idf.py build
            cd ../bastion
            idf.py build
          fi
